name = "HartReny"
version = "0.1.0"
defaultTargets = ["HartReny", "Challenge", "Solution"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "5e043698502894993991089b2dd893867c0db5c2"

[[lean_lib]]
name = "HartReny"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"
